added positionfilter to index
Mission-DMX/Docs pull request #14
Opened 2024-02-04 08:17 UTC by LRahlff

2024-02-04 08:18 UTC, LRahlff commented on Fish_Doku/Filter_Types.md
is this file enough as index, or does it has to be an README.md?

2024-02-05 13:34 UTC, Doralitze commented on Fish_Doku/Filter_Types.md
Maybe you should leaf it as an index and hint the existence of this file within the directories README.md.

2024-02-05 13:39 UTC, Doralitze requested changes
I think we should make a clear distinction between virtual filters (only handled by the GUI) and non-virtual ones (that therefore define an interface with fish). Maybe use a different directory. I  also think that these filters deserve an entry within the manual as they are quite complex to handle (albeit this does not need to be done now).

2024-02-05 16:00 UTC, LRahlff commented on Fish_Doku/README.md
did you mean like this?

2024-02-05 16:01 UTC, LRahlff commented
> I think we should make a clear distinction between virtual filters (only handled by the GUI) and non-virtual ones (that therefore define an interface with fish). Maybe use a different directory. I also think that these filters deserve an entry within the manual as they are quite complex to handle (albeit this does not need to be done now).

oh, yes i didnt know that in the editor filter were prepared too. what do you think of this structure? distinction between fish and gui and also between usage and technical information.

2024-02-07 14:08 UTC, Doralitze commented on Fish_Doku/README.md
Yes.

2024-02-07 14:11 UTC, Doralitze approved these changes
LGTM

2024-02-07 14:12 UTC, merged